# Generated by scripts/release.py from a release's published SHA256SUMS.
# Do not edit by hand: the next release overwrites this file, and a hand-edited
# checksum is exactly how v1.0.12 shipped a formula that could not install.
class Wizard < Formula
  desc "Local-first autonomous data analysis agent"
  homepage "https://wizardw2.vercel.app/"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.13/Wizard-v1.0.13-darwin-arm64.zip"
      sha256 "a20731f4fef085a0551823af6e4362b2060f4b298b0f1579d3ed19967b033e4d"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.13/Wizard-v1.0.13-darwin-amd64.zip"
      sha256 "99a717a18230c404505cfcf9011adb6c5e9dbe532430358e1d0ab6bf71995ded"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.13/Wizard-v1.0.13-linux-arm64.zip"
      sha256 "56380f882fba1ce59fdc8ec0bc2e99bf0ea1aabd702b9c78e55bc7c44e8d3b0f"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.13/Wizard-v1.0.13-linux-amd64.zip"
      sha256 "028cd6077e7f36272bde48cf018b888a1de27afa30d4b428d90d925f15f5de75"
    end
  end

  def install
    # The archive is the whole application (backend/, frontend/, requirements)
    # plus the CLI. It belongs in libexec, not the keg root; the CLI finds it
    # from its own resolved path, so the symlink in bin/ works from anywhere.
    # Release ZIPs intentionally contain one versioned top-level directory so
    # direct installs can retain the previous package for rollback. Homebrew
    # owns the versioned keg already, and depending on its version it either
    # unpacks into that directory or strips it, so accept both layouts and
    # install the *contents* of the package under libexec; installing the
    # directory itself would make the launcher point at a nonexistent
    # libexec/cli/wizard.
    package_dir = Dir["*"].find { |e| File.directory?(e) && File.executable?(File.join(e, "cli", "wizard")) }
    package_dir = "." if File.executable?("cli/wizard")
    odie "Wizard release archive has no application directory" unless package_dir
    libexec.install Dir[File.join(package_dir, "*")]
    bin.install_symlink libexec/"cli/wizard"
  end

  def caveats
    <<~EOS
      Set Wizard up, then start it:

        wizard init
        wizard start

      Then open http://localhost:3000 in your browser.

      To upgrade, use Homebrew, then re-run init (your settings are kept):

        brew update && brew upgrade wizard
        wizard init

      If something looks wrong:  wizard doctor
    EOS
  end

  test do
    assert_match "wizard CLI v#{version}", shell_output("#{bin}/wizard --version")
    assert_match "Usage", shell_output("#{bin}/wizard --help")
  end
end
