# Generated by scripts/release.py from a release's published SHA256SUMS.
# Do not edit by hand: the next release overwrites this file, and a hand-edited
# checksum is exactly how v1.0.12 shipped a formula that could not install.
class Wizard < Formula
  desc "Local-first autonomous data analysis agent"
  homepage "https://wizardw2.vercel.app/"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.14/Wizard-v1.0.14-darwin-arm64.zip"
      sha256 "fb0272253f06d140d57cbdccc2d90ed283a1caa03280c8f4ad29d8aa7c2538fa"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.14/Wizard-v1.0.14-darwin-amd64.zip"
      sha256 "a104e1e93827d47e21f81297baf83fc6d14b4d00fdd91a59c8fcee06d4edb58a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.14/Wizard-v1.0.14-linux-arm64.zip"
      sha256 "8af5c78daa60adce5e3beaaba65443bb640fd3ea301f82dc9780223ce2534fa1"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.14/Wizard-v1.0.14-linux-amd64.zip"
      sha256 "f54b2ded978244b9dd0e920fee61f0e2c0da21bd9e667e84f1c2dff32e25687d"
    end
  end

  def install
    # The archive is the whole application (backend/, frontend/, requirements)
    # plus the CLI. It belongs in libexec, not the keg root; the CLI finds it
    # from its own resolved path, so the symlink in bin/ works from anywhere.
    # Release ZIPs intentionally contain one versioned top-level directory so
    # direct installs can retain the previous package for rollback. Homebrew
    # owns the versioned keg already, and depending on its version it either
    # unpacks into that directory or strips it, so accept both layouts and
    # install the *contents* of the package under libexec; installing the
    # directory itself would make the launcher point at a nonexistent
    # libexec/cli/wizard.
    package_dir = Dir["*"].find { |e| File.directory?(e) && File.executable?(File.join(e, "cli", "wizard")) }
    package_dir = "." if File.executable?("cli/wizard")
    odie "Wizard release archive has no application directory" unless package_dir
    libexec.install Dir[File.join(package_dir, "*")]
    bin.install_symlink libexec/"cli/wizard"
  end

  def caveats
    <<~EOS
      Set Wizard up, then start it:

        wizard init
        wizard start

      Then open http://localhost:3000 in your browser.

      To upgrade, use Homebrew, then re-run init (your settings are kept):

        brew update && brew upgrade wizard
        wizard init

      If something looks wrong:  wizard doctor
    EOS
  end

  test do
    assert_match "wizard CLI v#{version}", shell_output("#{bin}/wizard --version")
    assert_match "Usage", shell_output("#{bin}/wizard --help")
  end
end
