# Generated by scripts/release.py from a release's published SHA256SUMS.
# Do not edit by hand: the next release overwrites this file, and a hand-edited
# checksum is exactly how v1.0.12 shipped a formula that could not install.
class Wizard < Formula
  desc "Local-first autonomous data analysis agent"
  homepage "https://wizardw2.vercel.app/"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.15/Wizard-v1.0.15-darwin-arm64.zip"
      sha256 "cfcc5fdaf57512c01f08a576f7e8653e42bf3c890c1ebb8b01592116091ac639"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.15/Wizard-v1.0.15-darwin-amd64.zip"
      sha256 "ec93d7cfddfac8c8759b69c3f86029e4441f68806dcd3de8f401a16e3fb33372"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.15/Wizard-v1.0.15-linux-arm64.zip"
      sha256 "7ba17be4e63f32185e3dbe1e2e0d001ee7097eb03460126a69d41f3c26229868"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.15/Wizard-v1.0.15-linux-amd64.zip"
      sha256 "5888ac9d0cf787c6897c8af08bf79b145a9c31770d8fffe3d8dfaee1605f1597"
    end
  end

  def install
    # The archive is the whole application (backend/, frontend/, requirements)
    # plus the CLI. It belongs in libexec, not the keg root; the CLI finds it
    # from its own resolved path, so the symlink in bin/ works from anywhere.
    # Release ZIPs intentionally contain one versioned top-level directory so
    # direct installs can retain the previous package for rollback. Homebrew
    # owns the versioned keg already, and depending on its version it either
    # unpacks into that directory or strips it, so accept both layouts and
    # install the *contents* of the package under libexec; installing the
    # directory itself would make the launcher point at a nonexistent
    # libexec/cli/wizard.
    package_dir = Dir["*"].find { |e| File.directory?(e) && File.executable?(File.join(e, "cli", "wizard")) }
    package_dir = "." if File.executable?("cli/wizard")
    odie "Wizard release archive has no application directory" unless package_dir
    libexec.install Dir[File.join(package_dir, "*")]
    bin.install_symlink libexec/"cli/wizard"
  end

  def caveats
    <<~EOS
      Set Wizard up, then start it:

        wizard init
        wizard start

      Then open http://localhost:3000 in your browser.

      To upgrade, use Homebrew, then re-run init (your settings are kept):

        brew update && brew upgrade wizard
        wizard init

      If something looks wrong:  wizard doctor
    EOS
  end

  test do
    assert_match "wizard CLI v#{version}", shell_output("#{bin}/wizard --version")
    assert_match "Usage", shell_output("#{bin}/wizard --help")
  end
end
