# Generated by scripts/release.py from a release's published SHA256SUMS.
# Do not edit by hand: the next release overwrites this file, and a hand-edited
# checksum is exactly how v1.0.12 shipped a formula that could not install.
class Wizard < Formula
  desc "Local-first autonomous data analysis agent"
  homepage "https://wizardw2.vercel.app/"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.12/Wizard-v1.0.12-darwin-arm64.zip"
      sha256 "3d1bee90b685e205476d515577fdb3d9b0a4fa0d5c6250223001f12d50678e47"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.12/Wizard-v1.0.12-darwin-amd64.zip"
      sha256 "63ce9b896c128949c8ccc35a455cb04ad2875fc8a713fc2e55a40ddf410675b9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.12/Wizard-v1.0.12-linux-arm64.zip"
      sha256 "080aeee38cdbae2f884a2566b755e1237ef83b2cfaad19ca8293c591f8665fa8"
    end
    on_intel do
      url "https://github.com/Wizard-AIA/Wizard-w2/releases/download/v1.0.12/Wizard-v1.0.12-linux-amd64.zip"
      sha256 "bf2c6a2b54d692a368af49e2e3e4b993721b64bf40581e073849af51d6c1a979"
    end
  end

  def install
    # The archive is the whole application (backend/, frontend/, requirements)
    # plus the CLI. It belongs in libexec, not the keg root; the CLI finds it
    # from its own resolved path, so the symlink in bin/ works from anywhere.
    # Release ZIPs intentionally contain one versioned top-level directory so
    # direct installs can retain the previous package for rollback. Homebrew
    # owns the versioned keg already, and depending on its version it either
    # unpacks into that directory or strips it, so accept both layouts and
    # install the *contents* of the package under libexec; installing the
    # directory itself would make the launcher point at a nonexistent
    # libexec/cli/wizard.
    package_dir = Dir["*"].find { |e| File.directory?(e) && File.executable?(File.join(e, "cli", "wizard")) }
    package_dir = "." if File.executable?("cli/wizard")
    odie "Wizard release archive has no application directory" unless package_dir
    libexec.install Dir[File.join(package_dir, "*")]
    bin.install_symlink libexec/"cli/wizard"
  end

  def caveats
    <<~EOS
      Set Wizard up, then start it:

        wizard init
        wizard start

      Then open http://localhost:3000 in your browser.

      To upgrade, use Homebrew, then re-run init (your settings are kept):

        brew update && brew upgrade wizard
        wizard init

      If something looks wrong:  wizard doctor
    EOS
  end

  test do
    assert_match "wizard CLI v#{version}", shell_output("#{bin}/wizard --version")
    assert_match "Usage", shell_output("#{bin}/wizard --help")
  end
end
